let piAccessToken = null;
function authHeaders(json=true){const h={};if(json)h['Content-Type']='application/json';if(piAccessToken)h.Authorization=`Bearer ${piAccessToken}`;return h}
async function api(path,options={}){const res=await fetch(`/api/${path}`,options);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
function friendlyDbError(error){return error?.message||String(error||'حدث خطأ غير متوقع')}
function initPi(){const btn=el('loginBtn');const incomplete=p=>console.log('Incomplete payment:',p);if(!window.Pi){btn.onclick=()=>showToast('Pi Browser Required','error');return}Pi.init({version:'2.0',sandbox:false});btn.onclick=async()=>{try{const auth=await Pi.authenticate(['username','payments'],incomplete);piAccessToken=auth.accessToken;await handleLogin()}catch(e){console.error(e);showToast(e.message||'Login failed','error')}}}
async function handleLogin(){try{const data=await api('session',{headers:authHeaders(false)});if(data.user.isBanned){el('banned-screen').classList.remove('hidden');el('banned-screen').style.display='flex';return}user={uid:data.user.uid,username:data.user.username};el('loginBtn').classList.add('hidden');el('headerUser').classList.remove('hidden');safeSetText('userDispName',user.username);el('profile-guest').classList.add('hidden');el('profile-user').classList.remove('hidden');safeSetText('p-username',user.username);await refreshTelegramButton();await Promise.all([loadMyAds(),loadInbox(),checkUnreadMessages()]);setInterval(checkUnreadMessages,10000)}catch(e){showToast(friendlyDbError(e),'error')}}
async function refreshTelegramButton(showErrors=false){const btn=el('telegramLinkBtn'),txt=el('telegramLinkText');if(!btn||!txt||!user)return;try{const d=await api('telegram-link',{headers:authHeaders(false)});btn.disabled=d.linked;btn.classList.toggle('btn-disabled',d.linked);txt.innerText=d.linked?(currentLang==='ar'?'تم الربط':'Linked'):(currentLang==='ar'?'ربط بوت تيليجرام':'Link Telegram Bot')}catch(e){if(showErrors)showToast(e.message,'error')}}
async function linkTelegramBot(){if(!user)return showToast('toast_login_first','error');try{const d=await api('telegram-link',{method:'POST',headers:authHeaders(),body:'{}'});openTelegramExternal(BOT_USERNAME,d.token);if(telegramCheckTimer)clearInterval(telegramCheckTimer);telegramCheckTimer=setInterval(()=>refreshTelegramButton(false),2500)}catch(e){showToast(e.message,'error')}}
async function loadAllProducts(){el('loading').style.display='block';try{const d=await api('public-products',{cache:'no-store'});globalProducts=(d.products||[]).sort(sortProductsByPromotion);renderProducts();openProductFromUrlOnce()}catch(e){safeSetHtml('products-list',`<div class="empty-state" style="grid-column:1/-1"><h3>خطأ</h3><p>${escapeHtml(e.message)}</p></div>`)}finally{el('loading').style.display='none'}}
async function openProductDetails(pid){const p=globalProducts.find(x=>x.id==pid);if(!p)return;try{const d=await api('public-products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:Number(pid)})});p.views=d.views||p.views}catch(_){}const images=Array.isArray(p.images)&&p.images.length?p.images:['https://placehold.co/600x600/f1f5f9/94a3b8?text=No+Image'];el('detail-slider').innerHTML=images.map(src=>`<div class="slide"><img src="${escapeAttr(src)}" class="slide-img"></div>`).join('');el('detail-dots').innerHTML=images.map((_,i)=>`<div class="dot ${i===0?'active':''}" onclick="goToSlide(${i})"></div>`).join('');safeSetText('detail-title',p.name);updateDetailPrice(p);safeSetText('detail-desc',p.description);safeSetText('detail-loc-text',`${p.country||''} - ${p.location||''}`);safeSetText('detail-views',formatCurrency(p.views||0));safeSetText('detail-seller-name',p.seller_username||'Unknown');safeSetText('detail-seller-avatar',(p.seller_username||'U').charAt(0).toUpperCase());const own=user&&p.seller_pi_id===user.uid;el('detail-actions').innerHTML=own?`<button onclick="openPromoteOptions(${Number(p.id)})" class="btn" style="width:100%">${escapeHtml(t('promote_ad_btn'))}</button><button onclick="deleteProduct(${Number(p.id)})" class="btn btn-danger" style="width:100%">${escapeHtml(t('delete_btn'))}</button>`:`<button onclick="openChatRoom(${Number(p.id)},'${escapeAttr(p.seller_pi_id)}','${escapeAttr(p.name)}','${escapeAttr(p.seller_username||'User')}')" class="btn btn-primary" style="width:100%">${escapeHtml(t('message_seller'))}</button>`;document.querySelectorAll('.view-section').forEach(e=>e.classList.add('hidden'));el('view-details').classList.remove('hidden')}
async function loadMyAds(){if(!user)return;const list=el('my-ads-list');try{const d=await api('products',{headers:authHeaders(false)}),products=d.products||[];safeSetText('stat-ads',products.length);safeSetText('stat-views',formatCurrency(products.reduce((s,p)=>s+(p.views||0),0)));list.innerHTML=products.map(p=>{const img=p.images?.[0]||'https://placehold.co/400x400';const state=p.status==='pending'?(currentLang==='ar'?'قيد المراجعة':'Pending'):p.status==='rejected'?(currentLang==='ar'?'مرفوض':'Rejected'):(currentLang==='ar'?'مقبول':'Approved');return `<div class="card" onclick="openProductDetails(${Number(p.id)})"><div class="card-img-wrap"><img src="${escapeAttr(img)}" class="card-img"></div><div class="card-body"><div class="card-title">${escapeHtml(p.name)}</div><div>${escapeHtml(state)}</div></div></div>`}).join('')||`<div class="empty-state"><h3>${escapeHtml(t('no_products'))}</h3></div>`}catch(e){list.innerHTML=`<div class="empty-state"><p>${escapeHtml(e.message)}</p></div>`}}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function submitProduct(){if(!user)return showToast('toast_login_first','error');const name=el('addName').value.trim(),price=Number(el('addPrice').value),description=el('addDesc').value.trim(),category=el('addCategory').value,country=el('addCountry').value,location=el('addState').value,btn=el('publishBtn');if(!name||description.length<10||!price||!category||!country||!location||selectedFiles.length<1||selectedFiles.length>3)return showToast('toast_fill_data','error');btn.disabled=true;try{const images=[];for(const file of selectedFiles){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('JPEG, PNG, WEBP only');const compressed=await imageCompression(file,{maxSizeMB:.8,maxWidthOrHeight:1600,useWebWorker:true,fileType:'image/jpeg'});images.push({data:await fileToDataUrl(compressed)});}await api('products',{method:'POST',headers:authHeaders(),body:JSON.stringify({name,description,priceUsd:price,category,country,location,images})});showToast(currentLang==='ar'?'تم إرسال الإعلان للمراجعة':'Ad sent for review','success');closeAddModal();await loadMyAds()}catch(e){showToast(e.message,'error')}finally{btn.disabled=false;btn.innerHTML=t('publish_btn')}}
async function deleteProduct(id){if(!confirm(t('confirm_delete')))return;try{await api('products',{method:'DELETE',headers:authHeaders(),body:JSON.stringify({id})});await Promise.all([loadMyAds(),loadAllProducts()]);nav('home')}catch(e){showToast(e.message,'error')}}
function openPromoteOptions(id){currentPromoteProductId=id;renderPromotionPlanPrices();el('promoteModal').style.display='flex'}function closePromoteModal(){el('promoteModal').style.display='none';currentPromoteProductId=null}function triggerPayment(_usd,_days,tier){if(!currentPromoteProductId)return;const id=currentPromoteProductId;closePromoteModal();promoteProduct(id,tier)}
async function promoteProduct(productId,tier){if(!window.Pi||!user)return showToast('Pi Browser Required','error');const plan={1:1,2:5,3:10}[tier];try{await refreshPiPrice();const amount=Number((plan/piUsdPrice).toFixed(8));Pi.createPayment({amount,memo:`Promote Ad ${productId}`,metadata:{type:'promotion',productId:Number(productId),tier:Number(tier)}},{onReadyForServerApproval:async paymentId=>{await api('approve',{method:'POST',headers:authHeaders(),body:JSON.stringify({paymentId})})},onReadyForServerCompletion:async(paymentId,txid)=>{await api('complete',{method:'POST',headers:authHeaders(),body:JSON.stringify({paymentId,txid})});showToast('Promotion Active!','success');await loadAllProducts()},onCancel:()=>showToast('Payment Cancelled','warning'),onError:e=>showToast(e.message||'Payment Failed','error')})}catch(e){showToast(e.message,'error')}}
function openChatRoom(pid,otherId,pName,uName){if(!user)return showToast('toast_login_first','error');activeChat={pid,otherId};safeSetText('chatTitle',pName);safeSetText('chatPeer',uName);el('chatModal').style.display='flex';loadMessages();api('messages',{method:'PATCH',headers:authHeaders(),body:JSON.stringify({productId:pid,otherPiId:otherId})}).catch(()=>{})}
async function loadMessages(){if(!activeChat)return;const d=await api(`messages?productId=${encodeURIComponent(activeChat.pid)}`,{headers:authHeaders(false)});el('msgContainer').innerHTML='';(d.messages||[]).filter(m=>(m.sender_pi_id===user.uid&&m.receiver_pi_id===activeChat.otherId)||(m.sender_pi_id===activeChat.otherId&&m.receiver_pi_id===user.uid)).forEach(renderMsg)}
function renderMsg(m){const div=document.createElement('div');div.className=`bubble ${m.sender_pi_id===user.uid?'me':'other'}`;div.innerText=m.content;el('msgContainer').appendChild(div)}
async function sendMsg(){const inp=el('msgInput');if(!activeChat||!inp.value.trim())return;try{await api('messages',{method:'POST',headers:authHeaders(),body:JSON.stringify({productId:activeChat.pid,receiverPiId:activeChat.otherId,content:inp.value.trim()})});inp.value='';await loadMessages()}catch(e){showToast(e.message,'error')}}
function closeChat(){el('chatModal').style.display='none';activeChat=null}
async function loadInbox(){if(!user)return;const list=el('inbox-list');try{const d=await api('messages',{headers:authHeaders(false)}),threads=new Map();(d.messages||[]).slice().reverse().forEach(m=>{const other=m.sender_pi_id===user.uid?m.receiver_pi_id:m.sender_pi_id,key=`${m.product_id}_${other}`;if(!threads.has(key))threads.set(key,{pid:m.product_id,otherId:other,pName:m.products?.name||'Item',last:m.content,name:m.sender_pi_id===other?m.sender_username:m.receiver_username,unread:!m.is_read&&m.receiver_pi_id===user.uid})});list.innerHTML=[...threads.values()].map(x=>`<div class="inbox-item ${x.unread?'unread':''}" onclick="openChatRoom(${x.pid},'${escapeAttr(x.otherId)}','${escapeAttr(x.pName)}','${escapeAttr(x.name)}')"><div class="inbox-info"><div class="inbox-name">${escapeHtml(x.name)}</div><div class="inbox-msg">${escapeHtml(x.last)}</div></div></div>`).join('')||`<div class="empty-state"><h3>${escapeHtml(t('no_messages'))}</h3></div>`}catch(e){list.innerHTML=`<p>${escapeHtml(e.message)}</p>`}}
async function checkUnreadMessages(){if(!user)return;try{const d=await api('messages',{headers:authHeaders(false)}),count=(d.messages||[]).filter(m=>!m.is_read&&m.receiver_pi_id===user.uid).length,b=el('chat-badge');if(count){b.innerText=count>9?'+9':count;b.classList.remove('hidden')}else b.classList.add('hidden')}catch(_){}}
document.addEventListener('DOMContentLoaded',()=>{updateLanguage();initDragAndDrop();initPi();refreshPiPrice();loadAllProducts();initLocations()});setInterval(refreshPiPrice,60000);
