let token=localStorage.getItem('dw_token')||'';let me=JSON.parse(localStorage.getItem('dw_user')||'null');let currentListing=null;let piReady=false;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h,cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function usd(v){return '$'+Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2})}function pi(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:4})+' π'}
function fmtDate(d){if(!d)return'';return new Date(d).toLocaleDateString('ar-EG',{day:'numeric',month:'long',year:'numeric'})}
function condition(v){return({new:'جديد',like_new:'كالجديد',used:'مستعمل'})[v]||v}
async function ensureMe(){if(!token)return null;try{const r=await api('/api/me');me=r.user;localStorage.setItem('dw_user',JSON.stringify(me));return me}catch{return null}}
async function piLogin(){try{if(!window.Pi)throw new Error('افتح الموقع داخل Pi Browser');const cfg=await fetch('/api/config').then(r=>r.json());if(!piReady){Pi.init({version:'2.0',sandbox:!!cfg.piSandbox});piReady=true}const a=await Pi.authenticate(['username','payments'],()=>{});const r=await fetch('/api/auth/pi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessToken:a.accessToken})}).then(r=>r.json());if(!r.token)throw new Error(r.error||'فشل تسجيل الدخول');token=r.token;me=r.user;localStorage.setItem('dw_token',r.token);localStorage.setItem('dw_user',JSON.stringify(r.user));return true}catch(e){toast(e.message);return false}}
function setMainImage(url,i){const im=$('#mainProductImage');if(im)im.src=url;document.querySelectorAll('.listing-thumbs button').forEach((b,n)=>b.classList.toggle('active',n===i))}
async function favorite(){if(!me&&!(await piLogin()))return;try{await api('/api/favorites/'+currentListing.id,{method:'POST'});toast('تم حفظ الإعلان في المفضلة')}catch(e){toast(e.message)}}
async function contactSeller(){if(!me&&!(await piLogin()))return;try{const r=await api('/api/chats',{method:'POST',body:JSON.stringify({listing_id:currentListing.id})});location.href='/chats.html?chat='+encodeURIComponent(r.data.id)}catch(e){toast(e.message)}}
function shareListing(){const url=location.href;if(navigator.share)navigator.share({title:currentListing.title,url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>toast('تم نسخ رابط الإعلان'))}
async function loadSimilar(id){try{const rows=await api('/api/listings/'+id+'/similar');if(!rows.length)return;$('#similarSection').innerHTML=`<h2 class="page-section-title">إعلانات مشابهة</h2><div class="similar-list">${rows.map(l=>`<a class="similar-item" href="/listing.html?id=${encodeURIComponent(l.id)}"><img src="${esc(l.image_urls?.[0]||'')}" alt="${esc(l.title)}"><div><b>${esc(l.title)}</b><div class="price">${Number(l.price_usd)>0?usd(l.price_usd):pi(l.price_pi)}</div></div></a>`).join('')}</div>`}catch{}}
async function loadListing(){const id=new URLSearchParams(location.search).get('id');if(!id){$('#listingContent').innerHTML='رابط الإعلان غير صحيح';return}await ensureMe();try{const {data:l}=await api('/api/listings/'+encodeURIComponent(id));currentListing=l;document.title=l.title+' — DealWay';const s=l.profiles||{},imgs=(l.image_urls||[]).slice(0,3);$('#listingContent').className='listing-detail-grid';$('#listingContent').innerHTML=`<section><div class="listing-gallery-card"><div class="listing-main-image"><img id="mainProductImage" src="${esc(imgs[0]||'')}" alt="${esc(l.title)}"></div>${imgs.length>1?`<div class="listing-thumbs">${imgs.map((u,i)=>`<button class="${i===0?'active':''}" type="button" style="background-image:url('${esc(u)}')" onclick="setMainImage('${esc(u)}',${i})" aria-label="الصورة ${i+1}"></button>`).join('')}</div>`:''}</div><div class="card" style="margin-top:12px"><h2 style="margin-top:0">وصف المنتج</h2><div class="listing-desc">${esc(l.description)}</div></div></section><aside class="listing-info-card"><h1 class="listing-title">${esc(l.title)}</h1><div class="listing-price">${Number(l.price_usd)>0?usd(l.price_usd):pi(l.price_pi)}</div>${Number(l.price_usd)>0?`<div class="listing-subprice">≈ ${pi(l.price_pi)} حسب سعر Pi الحالي</div>`:''}<div class="listing-meta"><span>${esc(condition(l.condition))}</span>${l.city?`<span>${esc(l.city)}</span>`:''}${l.area?`<span>${esc(l.area)}</span>`:''}${l.negotiable?'<span>قابل للتفاوض</span>':''}${l.delivery_available?'<span>توصيل متاح</span>':''}<span>${Number(l.views||0)} مشاهدة</span>${l.created_at?`<span>${fmtDate(l.created_at)}</span>`:''}</div><div class="seller-card"><div class="chat-avatar">${esc((s.display_name||s.pi_username||'P')[0])}</div><div><b>${esc(s.display_name||s.pi_username||'مستخدم Pi')}</b><div class="muted">${s.pi_username?'@'+esc(s.pi_username)+' · ':''}${Number(s.rating||0).toFixed(1)} ★ ${s.is_verified?'· موثق':''}</div></div></div><div class="listing-actions">${me?.id===l.seller_id?`<a class="btn primary" href="/account.html">إدارة الإعلان</a>`:`<button class="btn primary" onclick="contactSeller()">مراسلة البائع</button>`}<button class="btn outline" onclick="favorite()">حفظ في المفضلة</button><button class="btn outline" onclick="shareListing()">مشاركة الإعلان</button></div></aside>`;loadSimilar(l.id)}catch(e){$('#listingContent').className='empty';$('#listingContent').textContent=e.message}}
loadListing();
