const token=localStorage.getItem('dw_token')||'';let me=JSON.parse(localStorage.getItem('dw_user')||'null');const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const form=opt.body instanceof FormData;const h={...(form?{}:{'Content-Type':'application/json'}),...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h,cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}function img(l){return l.image_urls?.[0]||''}function usd(v){return '$'+Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2})}function pi(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:4})+' π'}
async function ensureMe(){if(!token)return null;try{const r=await api('/api/me');me=r.user;localStorage.setItem('dw_user',JSON.stringify(me));return me}catch{return null}}
async function piLogin(){try{if(!window.Pi)throw new Error('افتح الموقع داخل Pi Browser');const cfg=await fetch('/api/config').then(r=>r.json());Pi.init({version:'2.0',sandbox:!!cfg.piSandbox});const a=await Pi.authenticate(['username','payments'],()=>{});const r=await fetch('/api/auth/pi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessToken:a.accessToken})}).then(r=>r.json());if(!r.token)throw new Error(r.error||'فشل تسجيل الدخول');localStorage.setItem('dw_token',r.token);localStorage.setItem('dw_user',JSON.stringify(r.user));location.reload()}catch(e){toast(e.message)}}
function requireAuth(){if(token)return true;document.querySelector('#pageContent').innerHTML='<div class="card empty"><b>سجل دخولك عبر Pi أولًا</b><div style="margin-top:14px"><button class="btn primary" onclick="piLogin()">دخول Pi</button></div></div>';return false}
async function loadFavorites(){if(!requireAuth())return;try{const rows=await api('/api/favorites');const a=rows.map(x=>x.listings).filter(Boolean);$('#pageContent').innerHTML=a.length?'<div class="grid">'+a.map(l=>`<article class="item" onclick="location.href='/?listing=${l.id}'"><div class="thumb" style="background-image:url('${esc(img(l))}')"></div><div class="body"><div class="price">${Number(l.price_usd)>0?usd(l.price_usd):pi(l.price_pi)}</div><b>${esc(l.title)}</b></div></article>`).join('')+'</div>':'<div class="empty">لا توجد إعلانات محفوظة.</div>'}catch(e){toast(e.message)}}
let activeChat='';async function loadChats(selected){if(!requireAuth())return;try{const rows=await api('/api/chats');$('#pageContent').innerHTML=`<div class="chatwrap"><div class="chatlist">${rows.length?rows.map(c=>`<div class="chatrow" onclick="openChat('${c.id}')"><b>${esc(c.listings?.title||'محادثة')}</b><div class="muted">${esc((c.messages||[]).at(-1)?.body||'ابدأ المحادثة')}</div></div>`).join(''):'<div class="empty">لا توجد محادثات</div>'}</div><div id="chatpane"><div class="empty">اختر محادثة</div></div></div>`;if(selected||rows[0])openChat(selected||rows[0].id)}catch(e){toast(e.message)}}
async function openChat(id){activeChat=id;const msgs=await api('/api/chats/'+id+'/messages');$('#chatpane').innerHTML=`<div class="messages" id="messages">${msgs.map(m=>`<div class="bubble ${m.sender_id===me?.id?'me':''}">${esc(m.body)}</div>`).join('')}</div><form class="compose" onsubmit="sendMsg(event,'${id}')"><input class="field" name="body" placeholder="اكتب رسالة..."><button class="btn primary">إرسال</button></form>`;const x=$('#messages');x.scrollTop=x.scrollHeight}
async function sendMsg(e,id){e.preventDefault();const b=new FormData(e.target).get('body').trim();if(!b)return;await api('/api/chats/'+id+'/messages',{method:'POST',body:JSON.stringify({body:b})});e.target.reset();openChat(id)}
let files=[];async function loadSell(){if(!requireAuth())return;const cats=await api('/api/categories');$('#pageContent').innerHTML=`<form class="card form" onsubmit="submitSell(event)"><input class="field" name="title" required placeholder="عنوان الإعلان"><select name="category_id" required><option value="">اختر القسم</option>${cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><textarea name="description" rows="5" required placeholder="وصف المنتج"></textarea><div class="row2"><input class="field" type="number" step="0.01" min="0.01" name="price_usd" required placeholder="السعر بالدولار"><select name="condition"><option value="new">جديد</option><option value="like_new">كالجديد</option><option value="used">مستعمل</option></select></div><div class="row2"><input class="field" name="city" placeholder="المدينة"><input class="field" name="area" placeholder="المنطقة"></div><label class="card" style="margin:0;cursor:pointer">اختر من 1 إلى 3 صور<input id="imgs" hidden type="file" accept="image/*" multiple onchange="pickImgs(this)"></label><div class="previews" id="previews"></div><div class="row2"><label><input type="checkbox" name="negotiable"> قابل للتفاوض</label><label><input type="checkbox" name="delivery_available"> توصيل متاح</label></div><button class="btn primary">نشر الإعلان</button></form>`}
async function compress(file){const b=await createImageBitmap(file),m=1600,sc=Math.min(1,m/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.round(b.width*sc);c.height=Math.round(b.height*sc);c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close?.();return new Promise((ok,no)=>c.toBlob(x=>x?ok(new File([x],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'})):no(new Error('فشل ضغط الصورة')),'image/webp',.78))}
async function pickImgs(inp){const a=[...inp.files];if(a.length<1||a.length>3)return toast('اختر من 1 إلى 3 صور');files=[];for(const f of a)files.push(await compress(f));$('#previews').innerHTML=files.map(f=>`<div class="preview" style="background-image:url('${URL.createObjectURL(f)}')"></div>`).join('')}
async function submitSell(e){e.preventDefault();if(files.length<1)return toast('صورة واحدة على الأقل مطلوبة');try{const fd=new FormData();files.forEach(f=>fd.append('images',f));const up=await api('/api/uploads/listing-images',{method:'POST',body:fd});const f=new FormData(e.target),b=Object.fromEntries(f);b.price_usd=Number(b.price_usd);b.negotiable=f.has('negotiable');b.delivery_available=f.has('delivery_available');b.image_urls=up.urls||up.data||[];await api('/api/listings',{method:'POST',body:JSON.stringify(b)});toast('تم نشر الإعلان');setTimeout(()=>location.href='/account.html',800)}catch(e){toast(e.message)}}
async function loadAccount(){if(!requireAuth())return;await ensureMe();if(!me)return requireAuth();let listings=[];try{listings=await api('/api/my-listings')}catch{}$('#pageContent').innerHTML=`<div class="card profilehead"><div class="avatar">${esc((me.display_name||me.pi_username||'P')[0])}</div><div><h2 style="margin:0">${esc(me.display_name||me.pi_username||'Pioneer')}</h2><div class="muted">@${esc(me.pi_username||'pioneer')} · ${Number(me.rating||0).toFixed(1)} ★</div></div></div><div class="actions"><a class="btn outline" href="/sell.html" style="display:grid;place-items:center;text-decoration:none">إضافة إعلان</a><a class="btn outline" href="/favorites.html" style="display:grid;place-items:center;text-decoration:none">المفضلة</a></div><h1 style="font-size:20px">إعلاناتي</h1>${listings.length?listings.map(l=>`<div class="card"><b>${esc(l.title)}</b><div class="muted">${Number(l.price_usd)>0?usd(l.price_usd):pi(l.price_pi)} · ${esc(l.status)}</div><div style="margin-top:9px"><button class="btn outline" onclick="location.href='/?listing=${l.id}'">عرض</button></div></div>`).join(''):'<div class="empty">لا توجد إعلانات بعد.</div>'}`}
