const $=s=>document.querySelector(s),token=localStorage.getItem('dw_token')||'';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let suggestTimer;
async function api(p,o={}){const h={'Content-Type':'application/json',...(o.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(p,{...o,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}function card(l){const price=DW.money(l.price_usd,l.price_pi);return `<a class="search-result-card" href="/listing.html?id=${encodeURIComponent(l.id)}"><img loading="lazy" src="${esc(l.image_urls?.[0]||'')}" alt="${esc(l.title)}"><div><div class="price">${price}</div><b>${esc(l.title)}</b><div class="muted">${esc(l.city||'')} · ${esc(l.categories?.name||'')}</div>${l.profiles?.is_verified?'<span class="trust-badge">✓ بائع موثق</span>':''}</div></a>`}
async function init(){try{const cats=await api('/api/categories');$('#categoryField').innerHTML=`<select id="category"><option value="">كل الأقسام</option>${cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select>`;const p=new URLSearchParams(location.search);['q','city','min','max','sort','condition'].forEach(k=>{const el=$('#'+k);if(el&&p.get(k))el.value=p.get(k)});runSearch(false)}catch(e){toast(e.message)}}
function suggest(v){clearTimeout(suggestTimer);if(v.trim().length<2){$('#suggestions').innerHTML='';return}suggestTimer=setTimeout(async()=>{try{const rows=await api('/api/search/suggestions?q='+encodeURIComponent(v));$('#suggestions').innerHTML=rows.map(x=>`<button onclick="document.querySelector('#q').value=${JSON.stringify(x.title)};runSearch()"><span>${esc(x.title)}</span><small>${esc(x.city||'')}</small></button>`).join('')}catch{}},180)}
function params(){const p=new URLSearchParams();['q','category','city','condition','min','max','sort'].forEach(k=>{const v=$('#'+k)?.value?.trim?.()??$('#'+k)?.value;if(v)p.set(k,v)});if($('#negotiable')?.checked)p.set('negotiable','true');if($('#delivery')?.checked)p.set('delivery','true');p.set('limit','30');return p}
async function runSearch(updateUrl=true){$('#suggestions').innerHTML='';const p=params();if(updateUrl)history.replaceState(null,'','/search.html?'+p.toString());$('#results').innerHTML='<div class="skeleton-card"></div><div class="skeleton-card"></div>';try{const out=await api('/api/listings?'+p.toString());$('#resultMeta').innerHTML=`<b>${out.count||out.data.length}</b> نتيجة ${token?'<button class="linklike" onclick="saveSearch()">حفظ هذا البحث</button>':''}`;$('#results').className='results-list';$('#results').innerHTML=out.data.length?out.data.map(card).join(''):'<div class="empty">لا توجد نتائج مطابقة.</div>';$('#filterCount').textContent=[...p.keys()].filter(k=>!['q','sort','limit'].includes(k)).length}catch(e){$('#results').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function resetFilters(){['category','city','condition','min','max'].forEach(k=>{const e=$('#'+k);if(e)e.value=''});$('#sort').value='newest';$('#negotiable').checked=false;$('#delivery').checked=false}
async function saveSearch(){const name=prompt('اسم البحث المحفوظ:',$('#q').value||'بحثي');if(!name)return;try{await api('/api/saved-searches',{method:'POST',body:JSON.stringify({name,filters:Object.fromEntries(params())})});toast('تم حفظ البحث وسيتم تنبيهك بالنتائج الجديدة')}catch(e){toast(e.message)}}
init();
