'use strict';
const {createClient}=require('@supabase/supabase-js');
const sb=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const PI='https://api.minepi.com/v2';
const PROMOTION_PLANS={1:{usd:1,days:3},2:{usd:5,days:7},3:{usd:10,days:14}};
const RENEWAL_PLAN={usd:1,days:30};
function err(m,c='PAYMENT_ERROR',s=400){const e=new Error(m);e.code=c;e.statusCode=s;throw e}
function body(req){try{return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}catch{err('Invalid JSON','INVALID_JSON')}}
async function piUser(req){const m=String(req.headers.authorization||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)err('Missing Pi access token','PI_TOKEN_MISSING',401);const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(`${PI}/me`,{headers:{Authorization:`Bearer ${m[1]}`,Accept:'application/json'},signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok||!j.uid)err('Invalid Pi access token','PI_TOKEN_INVALID',401);return{uid:String(j.uid)}}finally{clearTimeout(t)}}
async function piPayment(id){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(`${PI}/payments/${encodeURIComponent(id)}`,{headers:{Authorization:`Key ${process.env.PI_API_KEY}`,Accept:'application/json'},signal:c.signal}),j=await r.json().catch(()=>({}));if(!r.ok)err(j.message||'Cannot verify Pi payment','PI_VERIFY_FAILED',502);return j}finally{clearTimeout(t)}}
function metadata(p){try{return typeof p.metadata==='string'?JSON.parse(p.metadata||'{}'):(p.metadata||{})}catch{err('Invalid payment metadata','PAYMENT_METADATA_INVALID')}}
async function context(p,uid){const m=metadata(p),productId=Number(m.productId||m.product_id),type=String(m.type||'promotion').toLowerCase(),tier=Number(m.tier||m.level||1);if(!productId||String(p.user_uid)!==uid||!['promotion','renewal'].includes(type))err('Invalid payment metadata','PAYMENT_METADATA_INVALID');const plan=type==='renewal'?RENEWAL_PLAN:PROMOTION_PLANS[tier];if(!plan)err('Invalid payment plan','PAYMENT_PLAN_INVALID');const {data,error}=await sb.from('products').select('id,seller_pi_id,status,promoted_until,expires_at,renewal_count').eq('id',productId).single();if(error)throw error;if(data.seller_pi_id!==uid)err('You do not own this ad','PRODUCT_NOT_OWNED',403);if(type==='promotion'&&data.status!=='approved')err('Product is not eligible for promotion','PRODUCT_NOT_ELIGIBLE');return{productId,type,tier,plan,product:data}}
async function piPrice(){const c=new AbortController(),t=setTimeout(()=>c.abort(),6000);try{const r=await fetch('https://www.okx.com/api/v5/market/ticker?instId=PI-USDT',{signal:c.signal,headers:{Accept:'application/json'}}),j=await r.json().catch(()=>({})),p=Number(j.data?.[0]?.last);if(!r.ok||!p)err('Cannot verify PI price','PI_PRICE_UNAVAILABLE',502);return p}finally{clearTimeout(t)}}
function amount(p,plan,price){const expected=plan.usd/price,paid=Number(p.amount);if(!paid||Math.abs(paid-expected)/expected>.035)err('Payment amount does not match the selected package','PAYMENT_AMOUNT_MISMATCH');return paid}
async function approve(req,res,u){const b=body(req);if(!b.paymentId)err('paymentId is required','PAYMENT_ID_REQUIRED');const p=await piPayment(b.paymentId),ctx=await context(p,u.uid),price=await piPrice();amount(p,ctx.plan,price);if(p.status?.developer_approved)return res.json({approved:true,alreadyApproved:true});const r=await fetch(`${PI}/payments/${encodeURIComponent(b.paymentId)}/approve`,{method:'POST',headers:{Authorization:`Key ${process.env.PI_API_KEY}`,'Content-Type':'application/json'},body:'{}'}),j=await r.json().catch(()=>({}));if(!r.ok)err(j.message||'Pi approval rejected','PI_APPROVAL_FAILED',502);const {error}=await sb.from('payments').upsert({payment_id:b.paymentId,user_id:p.user_uid,product_id:ctx.productId,amount_pi:Number(p.amount),amount_usd:ctx.plan.usd,pi_usd_price:price,tier:ctx.type==='promotion'?ctx.tier:0,days:ctx.plan.days,status:'approved',payment_type:ctx.type,metadata:metadata(p),raw_payment:p},{onConflict:'payment_id'});if(error)throw error;return res.json({approved:true})}
async function complete(req,res,u){const b=body(req);if(!b.paymentId||!b.txid)err('paymentId and txid are required','PAYMENT_COMPLETE_DATA_REQUIRED');const existing=await sb.from('payments').select('payment_id,status,product_id,payment_type').eq('payment_id',b.paymentId).maybeSingle();if(existing.data?.status==='completed')return res.json({success:true,alreadyCompleted:true,type:existing.data.payment_type});const cr=await fetch(`${PI}/payments/${encodeURIComponent(b.paymentId)}/complete`,{method:'POST',headers:{Authorization:`Key ${process.env.PI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({txid:String(b.txid)})}),cj=await cr.json().catch(()=>({}));if(!cr.ok)err(cj.message||'Pi completion rejected','PI_COMPLETION_FAILED',502);const p=await piPayment(b.paymentId);if(!p.status?.developer_completed||!p.status?.transaction_verified||p.status?.cancelled||p.status?.user_cancelled)err('Payment is not fully verified','PAYMENT_NOT_VERIFIED');if(String(p.transaction?.txid||'')!==String(b.txid))err('Transaction id mismatch','TXID_MISMATCH');const ctx=await context(p,u.uid),price=await piPrice(),paid=amount(p,ctx.plan,price),now=new Date();const pay={payment_id:b.paymentId,user_id:p.user_uid,product_id:ctx.productId,txid:String(b.txid),amount_pi:paid,amount_usd:ctx.plan.usd,pi_usd_price:price,tier:ctx.type==='promotion'?ctx.tier:0,days:ctx.plan.days,status:'completed',payment_type:ctx.type,metadata:metadata(p),raw_payment:p,completed_at:now.toISOString()};const {error:payErr}=await sb.from('payments').upsert(pay,{onConflict:'payment_id'});if(payErr)throw payErr;let patch,resultDate;if(ctx.type==='promotion'){const base=ctx.product.promoted_until&&new Date(ctx.product.promoted_until)>now?new Date(ctx.product.promoted_until):now;base.setUTCDate(base.getUTCDate()+ctx.plan.days);resultDate=base.toISOString();patch={promoted_until:resultDate,promotion_tier:ctx.tier,promoted_level:ctx.tier,promoted_priority:ctx.tier,last_payment_id:b.paymentId,last_payment_txid:String(b.txid)}}else{const base=ctx.product.expires_at&&new Date(ctx.product.expires_at)>now?new Date(ctx.product.expires_at):now;base.setUTCDate(base.getUTCDate()+ctx.plan.days);resultDate=base.toISOString();patch={expires_at:resultDate,renewed_at:now.toISOString(),renewal_count:Number(ctx.product.renewal_count||0)+1,status:'approved',item_status:'available',last_payment_id:b.paymentId,last_payment_txid:String(b.txid)}}const {error:prodErr}=await sb.from('products').update(patch).eq('id',ctx.productId).eq('seller_pi_id',u.uid);if(prodErr)throw prodErr;await sb.from('notifications').insert({user_pi_id:u.uid,type:ctx.type,product_id:ctx.productId,title_ar:ctx.type==='renewal'?'تم تجديد الإعلان':'تم تمييز الإعلان',title_en:ctx.type==='renewal'?'Ad renewed':'Ad promoted',body_ar:`صالـح حتى ${resultDate}`,body_en:`Active until ${resultDate}`});return res.json({success:true,type:ctx.type,until:resultDate,tier:ctx.tier})}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{if(!process.env.PI_API_KEY)err('PI_API_KEY is not configured','PI_ENV_MISSING',500);const u=await piUser(req),a=String(req.query?.action||body(req).action||'').toLowerCase();if(a==='approve')return approve(req,res,u);if(a==='complete')return complete(req,res,u);err('Invalid payment action','PAYMENT_ACTION_INVALID')}catch(e){console.error('payments:',e);return res.status(e.statusCode||400).json({error:e.message,code:e.code||'PAYMENT_ERROR'})}};
